### ISSUE TITLE
Resize JPG change colors

### ISSUE THREAD

**Issue by veloso11** [spatie/image#102]
![image](https://user-images.githubusercontent.com/20184741/75083116-52cd0c80-5517-11ea-9a3c-b85cc86e069a.png)

In some JPG images after resize the colors change:

    Image::load('example.jpg')
    ->fit(Manipulations::FIT_MAX, $maxWidth, $maxHeight)
    ->save();

**Comment by ekstro** [comment]
Same here. Any fix?
