### ISSUE TITLE
Optimization options

### ISSUE THREAD

**Issue by nlemoine** [spatie/image#106]
I'm working on a managed shared host where I can't install the necessary binaries to optimize images (no root privileges). However, I can still use some [precompiled binaries](https://github.com/imagemin?q=bin&type=&language=).

To make everything work as expected, I need to set the binary path. `spatie/image-optimizer` provides a way to do this: 
https://github.com/spatie/image-optimizer/blob/master/src/Optimizers/BaseOptimizer.php#L25-L34

Unfortunately `spatie/image` doesn't. The optimization options passed throw the `optimize` method only allows an array that [will be json decoded](https://github.com/spatie/image/blob/master/src/Image.php#L135). 

Would you consider adding more control over this? A `setOptimizers` method for example?

**Comment by freekmurze** [comment]
Feel free to send a PR that makes it work for you. Make sure to include tests and updated docs. If the code is simple enough, I'll merge it in 👍

**Comment by nlemoine** [comment]
Not sure what way to take before submitting something. I'd like to get your feedback first. 

How about modifying the [`$binaryPath`](https://github.com/spatie/image-optimizer/blob/master/src/Optimizers/BaseOptimizer.php#L13) property and setting it to `static`?

```php
Spatie\ImageOptimizer\Optimizers\Jpegoptim::$binaryPath = '/custom/path/to/jpegoptim';
```

This would avoid making changes to `spatie/image`.
