### ISSUE TITLE
Call to undefined method Intervention/Image/ImageManager::load()

### ISSUE THREAD

**Issue by wivaku** [spatie/image#111]
```
composer require spatie/image
```

```
php -i | grep "EXIF Support"
EXIF Support => enabled
```

```
>>> Image::load('https://dummyimage.com/300')
PHP Error:  Call to undefined method Intervention/Image/ImageManager::load() in /.../vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 261
```

**Comment by freekmurze** [comment]
Our tests prove that the package is working correctly: https://github.com/spatie/image/actions/runs/372366866
The error must be caused by something specific to your setup.

**Comment by wivaku** [comment]
It happens with a fresh Laravel 8 install.  
I don't see `load` as a method in the `ImageManager` [documentation](http://image.intervention.io/use/basics). It does mention `make` is to be used to read an image.

This works (in Tinker): when using `make` to [load an image](http://image.intervention.io/api/make).
```
$manager = new Intervention\Image\ImageManager(array('driver' => 'imagick'));
$image = Image::make('https://dummyimage.com/300')
$image->width() // 300
```

```
composer require spatie/image
...
  - Installing intervention/image (2.5.1): Extracting archive
...
```

**Comment by freekmurze** [comment]
Please submit a PR with a failing test for me to fix.

**Comment by wivaku** [comment]
afraid that's beyond my skillset... 😉

**Comment by wivaku** [comment]
Seems it was a namespace issue, it was using the `Intervention\Image` class instead of `Spatie\Image`.
```
Spatie\Image\Image::load('https://dummyimage.com/300')->getHeight() // 300
```
