### ISSUE TITLE
tmp folder is removed by Spatie\Image\GlideConversion::save()

### ISSUE THREAD

**Issue by JonathanDoelan** [spatie/image#117]
On my production server I have the problem that `Spatie\Image\GlideConversion::save()` is responsible for deleting the temp folder (sys_temp_dir, upload_tmp_dir), which is really bad and gives me a big headache.

As soon as I comment out `rmdir($conversionResultDirectory);` in `Spatie\Image\GlideConversion::save()` it works (temp folder won’t be deleted):

```
if ($this->directoryIsEmpty($conversionResultDirectory) && $conversionResultDirectory !== '/tmp') {
    //rmdir($conversionResultDirectory);
}
```

So this line causes the issue.

I have to mention, that this issue could also be a problem with the impementation in `dmitrybubyakin/nova-medialibrary-field` which I am using and where the problem occurs. https://github.com/dmitrybubyakin/nova-medialibrary-field/issues/110

This leads me to the questions:
1. Is it because there is a wrong implementation in `dmitrybubyakin/nova-medialibrary-field`?
2. Is the part in `Spatie\Image\GlideConversion::save()` really necessary? Why should I delete the temp folder?
3. Wouldn’t it be better if we’d replace `$conversionResultDirectory !== '/tmp'` with `$conversionResultDirectory !== sys_get_temp_dir()` instead, in order to prevent deleting the temp-dir?

**Comment by freekmurze** [comment]
> Is it because there is a wrong implementation in dmitrybubyakin/nova-medialibrary-field?
I currently don't have the time to review other packages.

> Is the part in Spatie\Image\GlideConversion::save() really necessary? Why should I delete the temp folder?
I'm thinking it is necessary. Feel free to send a PR with improvements that work for you.

> Wouldn’t it be better if we’d replace $conversionResultDirectory !== '/tmp' with $conversionResultDirectory !== sys_get_temp_dir() instead, in order to prevent deleting the temp-dir?
That's a good idea, thanks for that PR!
