### ISSUE TITLE
Bump league/glide to 2.0

### ISSUE THREAD

**Issue by NKDM44** [spatie/image#127]
That wasn't a good idea.. conversions are broken.
Btw. 
 - Upgrading league/glide (1.7.0 => 2.0.x-dev e84ef23)
 - Upgrading spatie/image (1.10.2 => 1.10.3)

{
    "message": "Class 'League\\Glide\\ServerFactory' not found",
    "exception": "Error",
    "file": "/var/www/vendor/spatie/image/src/GlideConversion.php",
    "line": 130,
    "trace": [
        {
            "file": "/var/www/vendor/spatie/image/src/GlideConversion.php",
            "line": 80,
            "function": "createGlideServer",
            "class": "Spatie\\Image\\GlideConversion",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/spatie/image/src/Image.php",
            "line": 140,
            "function": "performManipulations",
            "class": "Spatie\\Image\\GlideConversion",
            "type": "->"
        },

**Comment by FrancoisVinatis** [comment]
https://github.com/spatie/laravel-medialibrary/issues/2326

**Comment by apatkinson** [comment]
Is there a plan for this to be completed in the near future?

**Comment by freekmurze** [comment]
@apatkinson if you need this fast, feel free to invest some time of your own and submit a non-breaking PR.

**Comment by Nielsvanpach** [comment]
This issue was solved in the latest release, so I'm closing this one.

**Comment by apatkinson** [comment]
The title for this issue is `bump to 2.0`, which still should happen at some point?

**Comment by nlemoine** [comment]
@freekmurze Actually, I believe this was a non breaking PR (https://github.com/spatie/image/pull/123#issuecomment-815627191)
