### ISSUE TITLE
Laravel - Could not find the image `testing.jpg` error

### ISSUE THREAD

**Issue by quintenbuis** [spatie/image#130]
I have an image: `storage/app/public/testing.jpg`. I load the image: `$image = Image::load(storage_path('app/public/'.$file))->optimize();` and then try to save it with `$image->save(storage_path('app/public/image.jpg'));` I get the following error `Could not find the image 'testing.jpg'`

**Comment by quintenbuis** [comment]
Fixed it. 😅 🔥

**Comment by GuyInDoubt** [comment]
But how?

**Comment by quintenbuis** [comment]
@GuyInDoubt I supplied the `Image::load()` with the wrong path. Try getting the path to your file via `dd() (laravel)` or `var_dump()`. If you are using laravel you can use `Storage::exists(...)` to check if the file is present.
