### ISSUE TITLE
FIT_FILL does not behave as described

### ISSUE THREAD

**Issue by adminfriso** [spatie/image#136]
Dear Spatie,

In the documentation it is said that ```Manipulations::FIT_FILL``` behaves like FIT_CONTAIN, but adding extra empty pixels. However it actually behaves like FIT_MAX and adding extra pixels.

Uploading an image from 200x100 and doing the manipulation ```->fit(Manipulations::FIT_FILL, 400, 400)``` results in the behaviour that the image does end up as 400x400 but it not upscales and it only remains 200x100 adding extra pixels to fill up the empty space.

complete function call (media-libary)
```
        $this->addMediaConversion('medium')
            ->performOnCollections($collection)
            ->format(Manipulations::FORMAT_PNG)
            ->fit(Manipulations::FIT_FILL, 400, 400);
```

I tried to chain function calls to behave like FIT_CONTAIN and FIT_FILL.

```
        $this->addMediaConversion('medium')
            ->performOnCollections($collection)
            ->format(Manipulations::FORMAT_PNG)
            ->fit(Manipulations::FIT_CONTAIN, 400, 400)
            ->fit(Manipulations::FIT_FILL, 400, 400);
```

I also tried it to manipulate it with the width operator.

```
$this->addMediaConversion('medium')
            ->performOnCollections($collection)
            ->format(Manipulations::FORMAT_PNG)
            ->width(400)
            ->fit(Manipulations::FIT_FILL, 400, 400);
```

However this does not result in the desired behaviour.

Is there a way to make a call to get the FIT_FILL behaviour as described?

Your products are amazing, and I already thank you for your help!

Greetings Friso

**Comment by freekmurze** [comment]
Hi, we currently don't have the time to look at this, but feel free to submit a PR with tests that fixes this.

**Comment by JeremyRed** [comment]
Greetings. I think this can be resolved with a documentation fix. I was also a little confused when I saw the docs describing the behaviours and seeing output that was a little different. I created a PR (#150) to copy the docs from Glide that describe the behaviours. They seemed to clear up my confusion.

It might be worth giving the `Manipulations::FIT_CROP` a try. This will resize your image and trim any excess to the dimensions you supplied. Also If you need to chain fit methods you can give the `apply` method a try. 

One of these should be able to do the desired behaviour that you are describing above. 

Example:
```php
# Crop
$this->addMediaConversion('medium')
         ->performOnCollections($collection)
         ->fit(Manipulations::FIT_CROP, 400, 400)

# apply()
$this->addMediaConversion('medium')
         ->performOnCollections($collection)
         ->fit(Manipulations::FIT_CONTAIN, 400, 400)
         ->apply() # Apply the contain change before running fill
         ->fit(Manipulations::FIT_FILL, 400, 400);
```
Apply reference here:
https://spatie.be/docs/image/v1/usage/advanced-manipulations#example-usage-1
