### ISSUE TITLE
Wrong resized size

### ISSUE THREAD

**Issue by bendadaniel** [spatie/image#141]
Hello,
when I am using function `$image->width(100)` or `$image->height(100)` to resize image by one side. Sometimes generated image has a few pixels more or less. 

**Usecase:**

`  $image = Image::load(public_path("/images/test.png"));`
`  $image->height(320);`
`  $image->save(public_path("/images/final.png"));`

If you use this source image it will generate image with height 318px **(not 320!)**

**Version:** 
1.1 (because there is no new docs and I need PHP7 support)

**Use this source image:**
![test](https://user-images.githubusercontent.com/15817021/132503089-c2533fc1-56ae-47d1-9d5a-302acb2ef477.png)

Thank you

**Comment by nlemoine** [comment]
This issue isn't spatie/image related. It comes from the Glide dependency: https://github.com/thephpleague/glide/pull/310

Sadly, it has been merged in Glide and released in [Glide 2.0](https://github.com/thephpleague/glide/releases/tag/2.0.0). 

But I cherry picked it and submitted a pull request that has been merged in Glide 1.x: https://github.com/thephpleague/glide/pull/321

Which spatie/image requires in its own 1.x branch: https://github.com/spatie/image/blob/1.10.5/composer.json

Update your dependencies to the last versions and you should have accurate resized images.

**Comment by bendadaniel** [comment]
@nlemoine 
Hello, thank you for your help and work! Problem solved by `composer require league/glide "1.6.1"`

Thank you
