### ISSUE TITLE
Symfony 6 compatibility

### ISSUE THREAD

**Issue by spackmat** [spatie/image#151]
Hi,

I recently upgraded an app to Symfony 6.0 that uses `spatie/browsershot`, which itself requires `spatie/image`. Both state compatibility with several versions of `symfony/process`, but not with version `^6.0` of it. I managed to fix this with the following require line in my app's composer.json:

    "symfony/process": "6.0.0 as 5.4",

That works fine, so it should be safe to allow version `^6.0` of `symfony/process` in both `spatie/image` and `spatie/browsershot`.

Greets!

**Comment by freekmurze** [comment]
Feel free to send a PR to add this!
