### ISSUE TITLE
Duplicate images with same filename when running many process

### ISSUE THREAD

**Issue by hapo-hoangnh** [spatie/image#162]
when I run multiple processes at the same time, with different folders and same filename (thumbnail.jpg). the following error will appear
```
ErrorException: unlink(/tmp/3f941a84b6feca53b6ca17ea91f7ddf6): No such file or directory in /home/forge/project/vendor/spatie/image/src/GlideConversion.php:141
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /home/forge/project/vendor/spatie/image/src/GlideConversion.php(141): unlink()
#2 /home/forge/project/vendor/spatie/image/src/Image.php(142): Spatie\Image\GlideConversion->save()
````
https://github.com/spatie/image/issues/84
a very similar error happened before but this is a different case. my fix currently is to set a different temporary directory (by setTemporaryDirectory) for each process.
```
Image::load($folder_path.'thumbnail.jpg')
     ->setTemporaryDirectory('/tmp/'.$process->id)
     ->width(300)
     ->height(300)
     ->optimize()
     ->save($folder_path.'thumbnail_300.jpg');
```

**Comment by freekmurze** [comment]
This problem doesn't seem to pop up much. I think it would be better if it would be fixed at Glide's side.
