### ISSUE TITLE
How to mention storage disk while saving image?

### ISSUE THREAD

**Issue by ChaudharyHabib** [spatie/image#165]
In laravel, while uploading the file, I can mention the disk (local, s3 etc)
`$uploadedFile->storeAs($folder, $filename, $disk);`

but how to achieve the same while saving the file using that package:

`Image::load($request->file('file')->getPathName())
->fit(Manipulations::FIT_STRETCH, 300, 300)
->save(storage_path('app/public/test99.png'));`

**Comment by freekmurze** [comment]
This package is framework agnostic and has no knowledge of a disk.
