### ISSUE TITLE
spatie/image vs intervention

### ISSUE THREAD

**Issue by amosmos** [spatie/image#20]
Not really an issue, just curiosity, what is the difference between your package and intervention. I want to use one and find it hard to choose...

Thanks!

**Comment by freekmurze** [comment]
Both are excellent choices, so you make a bad decision here.

Imo with intervention you've got a bit more control on how you want to convert stuff and ours is a little bit more developer friendly.

I suggest you take a look at both API's a pick the one that feels good to you.
