### ISSUE TITLE
[question] Method to extract exif?

### ISSUE THREAD

**Issue by tomvo** [spatie/image#30]
I checked the API but no references to a way to extra EXIF info from an image. I see you're using the glide library which should be able to provide this. Any hints on how to get the EXIF somehow?

**Comment by sebastiandedeyne** [comment]
What's your use case for this? This library is primarily for manipulating image, not reading / retrieving metadata, so not sure if it would really fit in to expose methods for this.

**Comment by tomvo** [comment]
Yeah I'm indeed already using your library for manipulating images, which was my first use case. Now I just want to store just a little bit more info about the images being uploaded. 
I know Intervention has this feature but I don't really want to include Intervention just for this.

**Comment by freekmurze** [comment]
I'm not opposed to adding exif reading functions to the package. 

I'd accept a PR that adds this is a non-breaking, testable way that works for most image types.

**Comment by veewee** [comment]
Little tip: don't use the PHP `exif_*` methods. The best way of extracting exif data is by using exiftool. Here is some old code for  reference: https://github.com/phpro/zf-filesystem/blob/master/src/Phpro/Filesystem/Process/ExifTool.php

**Comment by coudenysj** [comment]
Have a look at https://github.com/PHPExif/php-exif

**Comment by freekmurze** [comment]
Nice, thanks for the suggestion guys. 

Conclusion: it's best to use a dedicated tool to extract exif data.

**Comment by ultrasamad** [comment]
Nice package, but ff you can rotate an image with this package, then it makes sense to be able to peep into the `exif` information as well. For instance, if I take a photo and it comes with a wrong orientation, I might want to rotate it. But then I need to know the current orientation of the photo so I can rotate it appropriately.
Image manipulation is not complete without being able to view and even write into the exif information.
