### ISSUE TITLE
Problem with tmp directory

### ISSUE THREAD

**Issue by clementbirkle** [spatie/image#31]
Hello,

The library works on my local machine but not on my share hosting. Apparently, it's a problem with the tmp directory. 

Can you help me ? How i can set a new tmp path directory ?

The error is:
#57 {main}  
[2017-08-04 07:34:53] local.ERROR: League\Flysystem\Exception: Impossible to create the root directory "/tmp/phpZInt4l". in /home/52354634/www/toolcie/app/vendor/league/flysystem/src/Adapter/Local.php:106
Stack trace:
#0 /home/52354634/www/toolcie/app/vendor/league/flysystem/src/Adapter/Local.php(127): League\Flysystem\Adapter\Local->ensureDirectory('/tmp/phpZInt4l')
#1 /home/52354634/www/toolcie/app/vendor/league/flysystem/src/Filesystem.php(69): League\Flysystem\Adapter\Local->write('phpZInt4l/565f0...', '\xFF\xD8\xFF\xE0\x00\x10JFIF\x00\x01\x01\x00\x00...', Object(League\Flysystem\Config))
#2 /home/52354634/www/toolcie/app/vendor/league/glide/src/Server.php(528): League\Flysystem\Filesystem->write('phpZInt4l/565f0...', '\xFF\xD8\xFF\xE0\x00\x10JFIF\x00\x01\x01\x00\x00...')
#3 /home/52354634/www/toolcie/app/vendor/spatie/image/src/GlideConversion.php(50): League\Glide\Server->makeImage('phpZInt4l', Array)
#4 /home/52354634/www/toolcie/app/vendor/spatie/image/src/Image.php(99): Spatie\Image\GlideConversion->performManipulations(Object(Spatie\Image\Manipulations))

**Comment by freekmurze** [comment]
There currently is no way to set the temp directory. I'd accept a PR that adds this in an easy to use, non breaking, fully tested way.

**Comment by clementbirkle** [comment]
Thank you for your fast response. Finally, I just added in my php.ini: upload_tmp_dir=x and now it works well :)

**Comment by vesper8** [comment]
that's a big problem! i'm having the same problem.. having to modify the php.ini shouldn't be the accepted solution..
