### ISSUE TITLE
Can't resize into fixed size ? 

### ISSUE THREAD

**Issue by shankhadevpadam** [spatie/image#32]
I have convert the image with dimension 1024x768 with parameter 100x100 but the converted image has not the dimension 100x100. But i have used intervention image before it convert the image as you like. But this package, it convert the image using aspect ratio. How to fix this problem.

**Comment by freekmurze** [comment]
You'll want to to a `fit` operation.

Under the hood our image package is used to perform the manipulations. Here's the relevant section in the docs:
https://docs.spatie.be/image/v1/image-manipulations/resizing-images#codemanipulationsfit-stretchcode
