### ISSUE TITLE
Add disk driver as second argument 

### ISSUE THREAD

**Issue by ekrist1** [spatie/image#39]
When saving images I´m using Storage::disk to set which disk driver to use:
`$filename = Storage::disk('public')->putFile('productimages', $file, 'public');`

It would be a nice feature to be able to use the load method like this _load($filename, 'public')_ instead of:
```
 SpatieImage::load(public_path('/storage/') . $filename)
                    ->quality(80)
                    ->width(640)
                    ->save();
```

**Comment by freekmurze** [comment]
The package is framework agnostic, so we are not going to add Laravel specific features.

If you need a powerful solution to handle images (and all sorts of files) in a Laravel app take a look at our medialibrary: https://docs.spatie.be/laravel-medialibrary/v6/introduction
