### ISSUE TITLE
Special character crashes on Image::load

### ISSUE THREAD

**Issue by fernandocoronatomf** [spatie/image#52]
Hi,

I am using the library and when I do Image::load($path) I got a exception if $path has special chars...

Is that a bug?

For Example: 39b896be-7982-11e8-a35e-08002769e491/télé.jpeg

Thanks

**Comment by freekmurze** [comment]
Seems like this is working correctly. If it should fail, submit a failing test for us to fix.
https://twitter.com/simo_benhida/status/1013732929254690816

**Comment by fernandocoronatomf** [comment]
@chapeupreto That is exactly the problem I have but my encoding is us-ascii
