### ISSUE TITLE
New logo/icon

### ISSUE THREAD

**Issue by mansya** [spatie/image#55]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by freekmurze** [comment]
We'd like our packages as simple as they can be. They should either all have a logo or none should have a logo. We don't want to spent our time maintaining / creating logos.

So thank you very much for your offer, but we are going to pass.
