### ISSUE TITLE
Portions of manipulated image are blank

### ISSUE THREAD

**Issue by kgenly** [spatie/image#57]
Portions of my manipulated images are blank (grey.) Usually just at the very bottom of the image, but in a few unfortunate cases more than 95% of my image just turns grey.

- The only manipulations I'm currently using are resizing and crop.
- I see no errors in the logs when this occurs.
- SOMETIMES regenerating/re-uploading the images fixes it, other times I just get more of the same.
- I am experiencing this issue when using spatie/image directly, and when working with spatie/laravel-media-library. I seem to experience it more when working with images being stored on S3, but not exclusively -- some local storage ones go off too.
- I can't predict when it will happen, but it seems to occur between 50-25% of the time, depending on who knows what.

Any ideas where I start to track this down?

![image](https://user-images.githubusercontent.com/8765196/44052741-4875de38-9ef2-11e8-9d7f-b68203f3ba16.png)
![image](https://user-images.githubusercontent.com/8765196/44052761-578f1c72-9ef2-11e8-998a-17926fc7ebc9.png)
![image](https://user-images.githubusercontent.com/8765196/44052820-9964f2de-9ef2-11e8-9176-dcda84c49367.png)

Any help is appreciated.

**Comment by marensas** [comment]
![image](https://user-images.githubusercontent.com/18376464/45563895-6458b200-b857-11e8-9d00-b5db8a6ff5bc.png)

Same problem.

**Comment by freekmurze** [comment]
I guess this problem is caused by memory or execution time constraints on your servers. Given enough memory / time every conversion should just work.

If you think that something can be improved in this package, feel free to send a PR.

**Comment by NickDunas** [comment]
I am having the exact same issue. It happens when S3 is used. I don't think that it is a memory or execution time issue as the conversion runs fast. It happens even when I just add a conversion through spatie/medialibrary with no actual conversions in it. Feels like it tries to download the original image, but it starts the conversion before the actual image is fully downloaded.

@kgenly and @marensas did you manage to find a solution to this?

**Comment by marensas** [comment]
@NickDunas As far as I remember, I'v got this only in my local ENV and this was related to memory issues. In staging/prod ENVs it was all ok.

**Comment by kgenly** [comment]
@NickDunas Same story here. It seemed to convert very fast, but as soon as I moved out of my staging and went to production it fixed itself. Not a very comforting answer, I'm sure.
