### ISSUE TITLE
temporary_directory_path not used in GlideConversion.php

### ISSUE THREAD

**Issue by flexelektro** [spatie/image#62]
The temp dir from the config file is not used in the GlideConversion.php, and automatically falls back to /tmp through calling sys_get_temp_dir().
/tmp often makes problems / is not readable on shared servers.

Really my only solution here is to hard code 
`
   $this->conversionResult = config('medialibrary.temporary_directory_path')
`
on line 50 in GlideConversion.php and 

```
$config = [
            'source' => dirname($inputFile),
            'cache' =>  config("medialibrary.temporary_directory_path"),
            'driver' => $this->imageDriver,
        ];
```
on line 80, so that the temp dir in from the config file is used.

In that state the library is not useable for me, because it does not run on many of my customers hostings...

**Comment by freekmurze** [comment]
Feel free to send a PR that adds a setter to set the temporary directory to be used. If no directory is use `sys_get_temp_dir()`.  Also add tests to make sure that it works

**Comment by fThues** [comment]
Thanks for your work! This issue just popped up on our staging system.

**Comment by freekmurze** [comment]
We'll handle this further in #66
