### ISSUE TITLE
Optimisation tools

### ISSUE THREAD

**Issue by nikona14** [spatie/image#64]
Since I have Windows Home on my machine, I'm having a hard time to install and setup optimization tools, where should I set up optimization tools in case I download them manually, and please also let me know which files should be inside the placed folders and what name they should have. Thanks <3

**Comment by freekmurze** [comment]
We are not Windows users, so we can't help you with this. Please ask on a public forum look stackoverflow.com

**Comment by nikona14** [comment]
I did that, twice. They keep downvoting and not even commenting why they downvote.

**Comment by freekmurze** [comment]
Maybe try a more welcoming crowd. I'm active in the Laravel community myself. Useful resources there are the forum on Laracasts or Laravel.io
