### ISSUE TITLE
Add exif PHP extension as installation requirement

### ISSUE THREAD

**Issue by AdrianHL** [spatie/image#67]
After https://github.com/spatie/image/commit/b5fbc88cc9791a99ea75159bc8e45d0c2de234ab this package requires exif PHP extension to be installed in the system. This has been rolled out in version 1.5.3 https://github.com/spatie/image/releases/tag/1.5.3

Could this be added to installation/requirements notes?

Thanks in advance

**Comment by freekmurze** [comment]
Feel free to PR this 👍

**Comment by AdrianHL** [comment]
Done now #68 
Thanks
