### ISSUE TITLE
Unable to get the width and height of modified image

### ISSUE THREAD

**Issue by e200** [spatie/image#72]
Unable to get the width and height of modified instance:

```php
$image = Image::load($imagePath); // 1024x730

$width = 700;
$height = 300;

$image->fit(
    Manipulations::FIT_MAX,
    $width,
    $height
);

$image->getWidth(); // 1024
$image->getHeight(); // 730
```
Instead of the size generated by this function through `Manipulations::FIT_MAX`.

**Comment by freekmurze** [comment]
I'm thinking the width and height are being cached on the instance.  Try adding 

```
Image::load($imagePath),
```

before the `getWidth` line.

Feel free to PR an improvement on this should you feel up to it.
