### ISSUE TITLE
Manipulation process suggestion

### ISSUE THREAD

**Issue by e200** [spatie/image#74]
What about replace the `manipulation process enqueue method` that this package uses to perform manipulations in favor of a `perform current method chain manipulation process` so we'll be able to retrieve updated image attributes like the current `width`, `height` or maybe the `binary/content` of the current manipulated data of the last chaining method?

Ex:

```php
$image = Image::load($path);

$image->content(); // uf7jxn9r4trg4
$image->width(); // 50

$image->crop(10, 10);

$image->content(); // 0s93k
$image->width(); // 10
```

Just an idea that I think would power up this package!

**Comment by freekmurze** [comment]
Feel free to PR non-breaking well tested features to this package 👍
