### ISSUE TITLE
Documentation page is not opening

### ISSUE THREAD

**Issue by sanjayojha** [spatie/image#83]
I am trying to access documentation [https://core.spatie.be/image](https://core.spatie.be/image) but getting 502 error

One more question what is the difference between this package and [laravel-glide](https://github.com/spatie/laravel-glide) ?

**Comment by atymic** [comment]
The docs are located here:
https://docs.spatie.be/image/v1/introduction/

Where did you get that URL from?

**Comment by freekmurze** [comment]
The dns records of our docs have been fixed. You should be able to see the docs now.

Our package provides a nice API around Glide.
