### ISSUE TITLE
Duplicate images with same filename

### ISSUE THREAD

**Issue by nlemoine** [spatie/image#84]
Hi, 

I'm facing a strange issue when some file have the same filename (but are in different folders). 

Here's the test case: https://www.dropbox.com/s/00nycs96n8vyfuy/duplicate-images.zip?dl=1

Just extract the archive, `cd` into the directory and run `php index.php`. 

One of the images with the same filename is duplicated. I tried to dig a little bit, looks like something goes wrong with in the `tmp` folder. I didn't have time to go further for now.

Could you have a look? You'll probably spot the issue faster than I do.

**Comment by freekmurze** [comment]
I'm sorry I don't have time to look into your specific project. Feel free to PR a failing test for me to solve.

**Comment by nlemoine** [comment]
Hello @freekmurze 

It's a a specific project, It's a basic test case demonstrating a bug, actually it is failing test. 

```php
use Spatie\Image\Image;
use Spatie\Image\Manipulations;

$images = [
	__DIR__ . '/src/08/image.jpg',
	__DIR__ . '/src/10/image.jpg',
];

foreach($images as $image) {
	$file_name = pathinfo($image, PATHINFO_FILENAME);
	$file_ext = pathinfo($image, PATHINFO_EXTENSION);
	$hash = md5($image);
	Image::load($image)
		->setTemporaryDirectory(__DIR__ . '/tmp')
		->sepia()
		->apply()
		->crop(Manipulations::CROP_CENTER, 100, 100)
	->save('dist/' . $file_name . '-' . $hash . '.' . $file_ext);
}

```

I'm not very confortable at unit testing but i'll try to PR something.
