### ISSUE TITLE
Possible to convert to different image type??

### ISSUE THREAD

**Issue by joshbruce** [spatie/image#90]
Have a PNG. Curious if I can convert them to a JPEG using the package. Not a deal breaker, just curious.

**Comment by freekmurze** [comment]
Not 100% sure, but I think you can do this by specifing the right extension when saving the file.

```
Image::load($pathToImage)
   ->width(100)
   ->height(100)
   ->save('new-image.jpg'); // it will save the file as a jpg
```

Inspect the filetype after this to be sure.
