### ISSUE TITLE
Support for AVIF ?

### ISSUE THREAD

**Issue by Nuranto** [spatie/image#92]
I know the support is still almost inexistant.... Just supported in Windows10 in their last update, and no browser supports it atm, as far as I know. (There is however a polyfill : https://github.com/Kagami/avif.js)
But the AVIF format was born earlier this year, and support will probably arrive soon everywhere.
The promise of this format is big, and it should - finally - be a real replacement for our current outdated formats (jpg, ..).

**Comment by freekmurze** [comment]
We're not going to invest time in this now, but if this can be easily added, I'd accept a PR.

**Comment by Nuranto** [comment]
Ok, I dug a little and I don't think it can be done yet, because the base lib used is GD, and GD is not compatible yet. 
For those who are interested, I posted an issue there : https://github.com/libgd/libgd/issues/557
