### ISSUE TITLE
Cropping without resizing

### ISSUE THREAD

**Issue by WiebeK** [spatie/image#95]
Hey,

I am using this package through the Laravel MediaLibrary. In my project I'm trying to crop a picture from the center, but it does a lot of resizing. Is there any way I can crop an image without it resizing?

**Code**
``` 
public function registerMediaConversions(Media $media = null) {
    $this->addMediaConversion('avatar')->crop('crop-center', 150, 150);
} 
```

**Images**
Input: https://i.imgur.com/SAOX2eX.jpg
Output: https://i.imgur.com/5Sj8aZo.jpg

Expected output (rough): https://i.imgur.com/IxcYkZz.png

**Comment by freekmurze** [comment]
Take a look at the `manualCrop` method: https://docs.spatie.be/image/v1/introduction/#cropping-the-starbucks-storefront
