### ISSUE TITLE
Adding watermark to existing (uploaded) image

### ISSUE THREAD

**Issue by aghayeff** [spatie/image#96]
I have an OpenCard web project. Want to apply a watermark to all images. 

`$imagePath = "blabla.jpg";`

//Adding watermark
`Image::load($imagePath)->watermark($watermarkImage)`

In my view:
`<img src="<?= imagePath ?>"`

At the end, it does not take any effect. 
What is wrong?

**Comment by freekmurze** [comment]
Make sure to call the `save` method. Take a look at our docs for a few examples.

**Comment by aghayeff** [comment]
Oo yeah. Cool. Is there any saveAs function? I didn't see on documentation
