### ISSUE TITLE
InvalidManipulation problem because of strtoupper

### ISSUE THREAD

**Issue by enescakir** [spatie/image#98]
I am trying to add crop conversion to my model.
`$this->addMediaConversion('test')->fit(Manipulations::FIT_CROP, 64,64)->performOnCollections('test')`

But it's throwing `InvalidManipulation` exception all the time if language is set to Turkish.

I tracked issue and `strtoupper('fit')` returns `FİT` in Turkish instead of `FIT`.

How can I solve this problem?

`mb_strtoupper('fit')` workings corrects and returns `FIT`. I can create PR for changing `strtoupper` with `mb_strtoupper` but it adds another dependency `ext-mbstring` to `composer.json`.

**Comment by freekmurze** [comment]
> I can create PR for changing strtoupper with mb_strtoupper but it adds another dependency ext-mbstring to composer.json.

Send a PR for this 👍
